[package]
name = "tabdiff"
version = "0.1.0"
edition = "2018"

[dependencies]
similar = { version = "2", features = ["inline"] }
csv = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"

console = "0.7"
